# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
# # Install the missing mdutils package
# !pip install mdutils
# %run initialise.py

In [2]:
import os
print(os.getcwd())
print(os.listdir()) # Check if 'initialise.py' appears in this list

/content
['.config', 'sample_data']


In [1]:
# If you are using Google Colab, the files aren't on the "cloud drive" by default. You have to pull them from GitHub first. Run this in a Colab cell:
# Corrected URLs and added missing files
!mkdir -p source # Create the source directory if it doesn't exist
!wget -O initialise.py https://raw.githubusercontent.com/rougier/numpy-100/master/initialise.py
!wget -O generators.py https://raw.githubusercontent.com/rougier/numpy-100/master/generators.py
!wget -O source/headers.ktx https://raw.githubusercontent.com/rougier/numpy-100/master/source/headers.ktx
!wget -O source/exercises100.ktx https://raw.githubusercontent.com/rougier/numpy-100/master/source/exercises100.ktx
!pip install mdutils
%run initialise.py

--2026-03-03 07:20:46--  https://raw.githubusercontent.com/rougier/numpy-100/master/initialise.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 251 [text/plain]
Saving to: ‘initialise.py’

initialise.py       100%[===================>]     251  --.-KB/s    in 0s      

2026-03-03 07:20:46 (3.26 MB/s) - ‘initialise.py’ saved [251/251]

--2026-03-03 07:20:46--  https://raw.githubusercontent.com/rougier/numpy-100/master/generators.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4421 (4.3K) [text/plain]
Saving to: ‘generators.py’

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [57]:
np.__version__

'2.0.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [53]:
np.empty(10)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [56]:
answer(3)

Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [39]:
# answer(4)
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

# Simpler alternative
print("%d bytes" % Z.nbytes)

800 bytes
800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [55]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [15]:
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [45]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [44]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data[1:100]

array([[3, 4],
       [5, 6]])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [64]:
a = np.zeros(4)
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [47]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [49]:
np.flip(Z)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [52]:
Z?

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [2]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [3]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [19]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.06237711 0.2652468  0.48105477]
  [0.14323529 0.40307238 0.04539163]
  [0.17913555 0.50973476 0.96503421]]

 [[0.40579302 0.13568719 0.40740508]
  [0.85378621 0.02431393 0.21850338]
  [0.24087253 0.63801055 0.75304622]]

 [[0.3034676  0.19328354 0.94439587]
  [0.30334871 0.96715341 0.18897157]
  [0.21584286 0.21916579 0.62598358]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [7]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


In [6]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.02118467179050887 0.9973545289904842


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [8]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.56205553406148


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [12]:
# A = np.zeros((5,5))
A = np.zeros((10,10))
A[0,] = 1
A[-1,] = 1
A[:,0] = 1
A[:,-1] = 1
print(A)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [11]:
# answer(15)
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [13]:
Z = np.ones((10,10))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
0.3 == 3 * 0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [24]:
Z = np.zeros((5,5))
Z[-1,:] = ((1,2,3,4,0))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 2. 3. 4. 0.]]


In [26]:
# answer(18)
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [11]:
answer(19)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


In [16]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1   # select row starting index 1 and every other row, and col index and every other col
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [78]:
a = np.random.randint(low=0, high=10, size=(6, 7, 8))
# np.argwhere(a == 100)
np.unravel_index(100, (6, 7, 8))

(np.int64(1), np.int64(5), np.int64(4))

In [80]:
# answer(20)
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [81]:
a = np.array([[1, 2], [3, 4]])
np.tile(a, (4, 4))

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [91]:
a = np.array([[1, 2], [3, 4]])
# np.tile(a, (4,1))
np.tile(a, (2, 1, 2))


# print(a)

array([[[1, 2, 1, 2],
        [3, 4, 3, 4]],

       [[1, 2, 1, 2],
        [3, 4, 3, 4]]])

In [89]:
np.shape([[1, 2], [3, 4]])

(2, 2)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [14]:
import numpy as np
a= np.random.randint(low=0, high=10, size=(5,5))
b = a - np.mean(a)/ np.std(a)
print(b)
# np.mean(a, axis=0)
# hint: (x -mean)/std

[[ 5.16296515 -1.83703485 -0.83703485  7.16296515  0.16296515]
 [ 1.16296515  1.16296515  0.16296515  4.16296515  2.16296515]
 [-0.83703485  0.16296515  3.16296515  4.16296515  3.16296515]
 [ 7.16296515  4.16296515  7.16296515  6.16296515  1.16296515]
 [ 4.16296515  5.16296515  3.16296515  3.16296515  2.16296515]]


In [12]:
# answer(22)
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.59522175 -1.40833875 -1.26708181 -0.26848682 -0.20143704]
 [-0.07636495  0.66490467 -1.01237976  1.33594712  1.42902094]
 [ 0.39998213 -1.32998992 -1.72446529  0.58188484 -0.68756339]
 [ 0.76085678  1.03733119 -1.27949721  0.91382268  1.25976447]
 [-0.89474427  0.42521437  1.66995558 -0.36251173 -0.56104558]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [16]:
# answer(23)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [20]:
a = np.random.randint(low=0, high=10, size=(5,3))
b = np.random.randint(low=0, high=10, size=(3,2))
# Corrected to matrix multiplication
result = a @ b
print(result)

[[ 80  97]
 [ 95 112]
 [ 29  21]
 [ 40  33]
 [ 44  47]]


In [21]:
# answer(24)
Z = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

Z = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [30]:
# answer(25)
Z = np.arange(11)
Z[(Z>3) & (Z<8)] *= -1 # Corrected: Added parentheses around comparisons
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [1]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
answer(26)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [18]:
Z = np.arange(10)
# print(Z**Z)
# print(2 << Z >> 2)
# print(Z <- Z)
# print(1j*Z)
# print(Z/1/1)
print(Z<Z>Z)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [34]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


/tmp/ipython-input-423/3034665705.py:1: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [33]:
import numpy as np

# Sample float array
Z = np.array([-1.5, -0.7, 0.0, 0.7, 1.5, 2.1, -2.9])
print("Original array:", Z)

# Round away from zero
# This works by taking the ceiling of the absolute value and then restoring the original sign.
rounded_away_from_zero = np.copysign(np.ceil(np.abs(Z)), Z)
print("Rounded away from zero:", rounded_away_from_zero)

# Example with positive numbers
Z_pos = np.array([1.2, 1.8, 0.1, 2.0])
rounded_pos = np.copysign(np.ceil(np.abs(Z_pos)), Z_pos)
print("\nOriginal positive array:", Z_pos)
print("Rounded positive away from zero:", rounded_pos)

# Example with negative numbers
Z_neg = np.array([-1.2, -1.8, -0.1, -2.0])
rounded_neg = np.copysign(np.ceil(np.abs(Z_neg)), Z_neg)
print("\nOriginal negative array:", Z_neg)
print("Rounded negative away from zero:", rounded_neg)

Original array: [-1.5 -0.7  0.   0.7  1.5  2.1 -2.9]
Rounded away from zero: [-2. -1.  0.  1.  2.  3. -3.]

Original positive array: [1.2 1.8 0.1 2. ]
Rounded positive away from zero: [2. 2. 1. 2.]

Original negative array: [-1.2 -1.8 -0.1 -2. ]
Rounded negative away from zero: [-2. -2. -1. -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [65]:
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])
np.intersect1d(a,b)

array([3, 4, 5])

In [19]:
answer(30)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
answer(31)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [21]:
np.emath.sqrt(-1)

np.complex128(1j)

In [22]:
import numpy as np

val1 = np.sqrt(-1)
val2 = np.emath.sqrt(-1)

print(f"np.sqrt(-1) is: {val1}")
print(f"np.emath.sqrt(-1) is: {val2}")
print(f"Is np.sqrt(-1) == np.emath.sqrt(-1)? {val1 == val2}")

np.sqrt(-1) is: nan
np.emath.sqrt(-1) is: 1j
Is np.sqrt(-1) == np.emath.sqrt(-1)? False


/tmp/ipykernel_424/1991443291.py:3: RuntimeWarning: invalid value encountered in sqrt
  val1 = np.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [23]:
import numpy as np
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

answer(33)

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [6]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [16]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(B)

[3. 3. 3.]


In [2]:
 import numpy as np
 np.ones(3)*2


array([2., 2., 2.])

In [17]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


In [32]:
import numpy as np
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(f"Final A: {A}")
print(f"Final B: {B}")

Final A: [-1.5 -1.5 -1.5]
Final B: [3. 3. 3.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [36]:
import numpy as np

Z = np.array([1.2, 2.2, 2.6, 3.1, 5])
print("Original array:", Z)

# Method 1: Using astype(int)
print("Method 1 (astype(int)):", Z.astype(int))

# Method 2: Using np.trunc
print("Method 2 (np.trunc):", np.trunc(Z))

# Method 3: Using np.floor
print("Method 3 (np.floor):", np.floor(Z))

# Method 4: Subtracting the remainder (Z - Z % 1)
print("Method 4 (Z - Z % 1):", Z - Z % 1)

Original array: [1.2 2.2 2.6 3.1 5. ]
Method 1 (astype(int)): [1 2 2 3 5]
Method 2 (np.trunc): [1. 2. 2. 3. 5.]
Method 3 (np.floor): [1. 2. 2. 3. 5.]
Method 4 (Z - Z % 1): [1. 2. 2. 3. 5.]


In [37]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [19]:
a = np.arange(4)
b = np.tile(a, (5,1))
print(b)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [23]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


In [24]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [27]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [28]:
np.arange(0, 5), (5,1)

(array([0, 1, 2, 3, 4]), (5, 1))

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [24]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


In [26]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [28]:
np.arange(0.1, 1, 0.1)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [31]:
# answer(39)
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [34]:
a = np.random.randint(low=0, high=10, size=10)
print(a)

b = np.sort(a)
print("sorted: ", b)

[6 6 7 6 2 6 6 4 6 5]
sorted:  [2 4 5 6 6 6 6 6 6 7]


In [35]:
answer(40)

Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [37]:
# answer(41)
Z = np.arange(10)
np.add.reduce(Z)

np.int64(45)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [40]:
a == b
np.allclose(a,b)

False

In [42]:
# answer(42)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [45]:
# answer(44)
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.28465803 0.93171919 0.74008017 0.28314078 0.72432925 1.1945651
 0.68211983 1.12314693 0.73924614 1.17521506]
[0.7521027  0.54720718 0.6994982  0.84102543 0.28989968 0.73514979
 0.59964883 0.5100073  0.93427862 0.73820405]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [49]:
a = np.random.randint(1,10,10)
print(a)
a[np.max(a)] = 0
print(a)

[7 6 1 8 1 5 3 2 8 6]
[7 6 1 8 1 5 3 2 0 6]


In [50]:
answer(45)

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [52]:
# answer(46)
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [53]:
answer(49)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [36]:
import numpy as np
Z = np.random.rand(3, 3)

# Calculate mean along axis 1 (rows)
row_means = Z.mean(axis=1, keepdims= True)
print(row_means)
Y= Z - row_means
print(Y)



[[0.42565439]
 [0.38520436]
 [0.63381566]]
[[-0.16560643 -0.11052972  0.27613615]
 [-0.30112511  0.52213417 -0.22100906]
 [ 0.06441884 -0.00157098 -0.06284786]]


In [37]:
answer(58)

# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)


[[0.26004796 0.31512467 0.70179054]
 [0.08407924 0.90733853 0.1641953 ]
 [0.6982345  0.63224467 0.5709678 ]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [ ]:
..

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)